#!/usr/bin/perl

use strict;
use Getopt::Long;

sub usage
{
 print '@BINPREFIX@preprocessor - preprocessor for models and LTL formulas'."\n";
 print "\n";
 print 'Usage: @BINPREFIX@preprocessor [-D definitions] [-h] source'."\n";
 print "\n";
 print '-D definitions ... use these definitions during preprocessing'."\n";
 print '-h             ... this help'."\n";
 print 'source         ... DVE, Promela or LTL source (extensions .mdve, mprobdve, .pml or .mltl)'."\n";
}

my $prep;
my $help;
GetOptions('D=s' => \$prep,
           'help' => \$help);

if (defined($help)) { usage(); exit 0; }
   
my $file = shift;
my $path_to_defs = '@M4_DEFS_PATH@/m4_defs';

if (!defined($file)) { usage(); print STDERR "\nError: Name of a file containing a source not given.\n"; exit 1; }

my @pom = split /[\s,]+/, $prep;
my $defs;
for (@pom) { $defs .= ' -D'.$_;}

if ($file =~ /^[^.]*$/) { warn 'Warning: no file extension - assuming Promela input'; }

if ($file =~ /\.mltl$/) {
    print `m4 $path_to_defs $defs $file`;
} elsif ($file =~ /\.mdve$/) {
    print `m4 $path_to_defs $defs $file`;
} elsif ($file =~ /\.mprobdve$/) {
    print `m4 $path_to_defs $defs $file`;
} elsif ($file =~ /\.pml$/ or $file =~ /^[^.]*$/) {
    print `cpp -P $defs $file`;
} else { $file =~ /\.[^.]*$/;
         die 'Error: Unknown extension "'.$&.'"'; }

