#!/usr/bin/perl

sub readfile {
	my ($f) = @_;
	my $in;
	open I, "$f";
	$in .= $_ while (<I>);
	close I;
	return $in;
}

my $h = &readfile( "hosts" );
open L, ">load";

for (split /\n/, $h) {
	my ($x, $m) = split (/: /);
	my $u = "";
	if ( system( "ping -c1 -W1 $m >& /dev/null" ) == 0 ) {
		$u = `ssh $m uptime`;
		$u =~ s/.*load average: ([0-9., ]+).*\n/$1/;
	}
	print L "$m: $u\n";
}

close(L);
