#!/usr/bin/perl

my $t = `cat model-type`;
my $p = `cat property-type`;
chomp( $t );
chomp( $p );
if ( $t eq "dve" ) {
	if ( $p eq "ltl" ) {
		link( "model", "model.dve" );
		link( "property", "property.ltl" );
		system( "divine.combine -p 1 -o model.dve property.ltl"
				. " > model.check || echo error combining > error" );
	} else { link( "model", "model.check" ); }
	my $t = `divine.syntax model.check 2>&1`;
	if ( $t =~ /^OK$/gsm ) {
		system( "echo syntax ok > ok" );
	} else {
		open ERR, ">error";
		print ERR $t;
		close( ERR );
	}
} elsif ( $t eq "pml" ) {
	mkdir( "foo" );
	link( "model", "foo/model" );
	system( "divine.pml2s.sh foo/model 2>&1 && echo ok > ok || echo error > error" );
}
