DiVinE: compressor_t Class Reference
compressor_t Class Reference
Compression implementation class.
#include <compressor.hh>
Public Member Functions
void clear ()
Clears data structures initialized inside compressor.
bool compress (state_t, char *&pointer, int &size)
Compress a state according current compression method.
bool decompress (state_t &, char *pointer, int size)
Decompress the state using current compression method.
bool init (int method, int appendix_size)
Initializes compressor instance.
Detailed Description
Compression implementation class.
Member Function Documentation
void clear ()
Clears data structures initialized inside compressor.
Dealocates data that are created during initialization of compressor. This is needed especially for clearing the arena of compressor.
Referenced by explicit_storage_t::init().
bool compress (state_t , char *& pointer, int & size)
Compress a state according current compression method.
Returns where the state is compressed and how long the compressed representation is.
Referenced by explicit_storage_t::insert(), explicit_storage_t::is_stored(), and explicit_storage_t::is_stored_if_not_insert().
bool decompress (state_t & , char * pointer, int size)
Decompress the state using current compression method.
Decompress the state from the given pointer and size using current compression method.
Referenced by explicit_storage_t::reconstruct().
bool init (int method, int appendix_size)
Initializes compressor instance.
Requires identification of compression method, extra space that should be allocated at each compressed state (appendix) and pointer to explicit_system_t.
Referenced by explicit_storage_t::init().
The documentation for this class was generated from the following file:
compressor.hh
Reference Manual for Library, 2006 developed in ParaDiSe laboratory, Faculty of Informatics, Masaryk University