DiVinE: system_trans_t Class Reference
system_trans_t Class Reference
Class storing informations about one system transition.
#include <system_trans.hh>
Public Member Functions
virtual system_trans_t & operator= (const system_trans_t &second)=0
An assignment operator.
system_trans_t ()
A constructor.
virtual std::string to_string () const =0
Returns a string representation of enabled transition.
virtual void write (std::ostream &ostr) const =0
virtual ~system_trans_t ()
A destructor.
Methods accessing transitions forming a system transition
These methods are implemented only if system_t::can_transitions() in the system that has generated the instance of this class returns true.
virtual size_int_t get_count () const =0
virtual transition_t *const & operator[] (const int i) const =0
Returns `i'-th transition forming this transition of the system.
virtual transition_t *& operator[] (const int i)=0
Returns `i'-th transition forming this transition of the system.
virtual void set_count (const size_int_t new_count)=0
Sets a count of transitions of processes forming this enabled transition.
Detailed Description
Class storing informations about one system transition.
System transition consists of several transitions (of type transition_t, iff system can work with transitions)
System transition represent the step of the entire system (compared to the transition_t, which represents the step of a single process).
Developer will usually use system_trans_t as its child enabled_trans_t which adds the "erroneous" property to this class.
Member Function Documentation
virtual size_int_t get_count () const [pure virtual]
Returns a count of transitions of processes forming this enabled transition
Implemented in bymoc_system_trans_t, and dve_system_trans_t.
Referenced by dve_explicit_system_t::get_property_trans(), dve_explicit_system_t::get_receiving_trans(), and dve_explicit_system_t::get_sync_enabled_trans_succ().
virtual system_trans_t& operator= (const system_trans_t & second) [pure virtual]
An assignment operator.
Makes a hard copy of system transition => takes a time O(second.size())
Implemented in bymoc_system_trans_t, and dve_system_trans_t.
virtual void write (std::ostream & ostr) const [pure virtual]
Prints a string representation of enabled trantition to output stream `ostr'
Implemented in bymoc_system_trans_t, and dve_system_trans_t.
The documentation for this class was generated from the following file:
system_trans.hh
Reference Manual for Library, 2006 developed in ParaDiSe laboratory, Faculty of Informatics, Masaryk University