DiVinE: dve_prob_explicit_system_t Class Reference
dve_prob_explicit_system_t Class Reference
Class in DVE system interpretation.
#include <dve_prob_explicit_system.hh>
Public Member Functions
dve_prob_explicit_system_t (error_vector_t &evect=gerr)
A constructor.
virtual int get_succs (state_t state, prob_succ_container_t &succs)
Creates probabilistic successors of state `state'.
virtual int get_succs (state_t state, prob_succ_container_t &succs, enabled_trans_container_t &etc)
Creates probabilistic successors of state `state'.
virtual int get_succs_ordered_by_prob_and_property_trans (state_t state, prob_succ_container_t &succs)
virtual slong_int_t read (const char *const filename)
Reads in a DVE source given by `filename'.
virtual slong_int_t read (std::istream &ins)
Implements system_t::read(std::istream & ins = std::cin) in DVE system.
virtual ~dve_prob_explicit_system_t ()
A destructor.
Detailed Description
Class in DVE system interpretation.
This class implements the abstract interface explicit_system_t.
It is a child of dve_system_t - thus it also contains the representation of DVE system.
DVE system interpretation in this case comprises state generation, enabled transitions generation and expression evaluation.
This implementation of the abstract interface implements full set of its methods. Furthermore It takes over the system of expression evaluation from system_t. Only for evaluating varibles, fields and state identifiers there are defined special functions, which return their value accoring a state of system (given by a piece of a memory).
Furthermore it provides the set of methods, which are purely DVE system specific.
Constructor & Destructor Documentation
dve_prob_explicit_system_t (error_vector_t & evect = gerr) [inline]
A constructor.
Parameters:
evect = error vector used for reporting of error messages
Member Function Documentation
virtual int get_succs (state_t state, prob_succ_container_t & succs) [inline, virtual]
Creates probabilistic successors of state `state'.
Creates probabilistic successors of state state and saves them to successor container succs (see prob_succ_container_t).
Parameters:
state = state of the system
succs = successors container for storage of successors of state
Returns:
bitwise OR of SUCC_NORMAL, SUCC_ERROR and SUCC_DEADLOCK (use functions succs_normal(), succs_error() and succs_deadlock() for testing)
Implements prob_explicit_system_t.
int get_succs (state_t state, prob_succ_container_t & succs, enabled_trans_container_t & etc) [virtual]
Creates probabilistic successors of state `state'.
Creates probabilistic successors of state state. In addition to get_succs(state_t state, prob_succ_container_t & succs) this method also creates a piece of information about enabled transitions used for successor generation.
Together with methods prob_system_t::get_prob_trans_of_trans(), prob_system_t::get_index_of_trans_in_prob_trans() and methods of prob_transition_t it is possible to extract all additional information (and even more) that is stored in prob_succ_container_t.
Implements prob_explicit_system_t.
References enabled_trans_container_t::clear(), array_t::clear(), transition_t::get_gid(), prob_system_t::get_index_of_trans_in_prob_trans(), prob_system_t::get_prob_trans_of_trans(), prob_system_t::get_prob_transition(), dve_explicit_system_t::get_property_trans(), dve_explicit_system_t::get_sending_or_normal_trans(), dve_explicit_system_t::get_succs(), prob_transition_t::get_weight(), prob_transition_t::get_weight_sum(), system_t::get_with_property(), array_t::push_back(), and array_t::size().
virtual slong_int_t read (const char *const filename) [inline, virtual]
Reads in a DVE source given by `filename'.
Is uses system_t::read(const char * const filename), therefore see that function for more information (about return value etc.) Furthermore, it makes some analysis and extraction of information from the system and symbol table
Reimplemented from dve_explicit_system_t.
References dve_explicit_system_t::read().
The documentation for this class was generated from the following files:
dve_prob_explicit_system.hh
dve_prob_explicit_system.cc
Reference Manual for Library, 2006 developed in ParaDiSe laboratory, Faculty of Informatics, Masaryk University