DiVinE: dve_process_decomposition_t Class Reference
dve_process_decomposition_t Class Reference
#include <dve_process_decomposition.hh>
Public Member Functions
dve_process_decomposition_t (dve_explicit_system_t &system)
int get_process_scc_id (state_t &)
int get_process_scc_type (state_t &)
int get_scc_count ()
int get_scc_type (int)
bool is_weak ()
void parse_process (std::size_t)
Detailed Description
This class is used to decompose a graph of a single process specified in a dve file into SCCs. The decomposition is not accesible directly but with member functions returning for a given state SCC id and type.
Member Function Documentation
int get_process_scc_id (state_t &) [virtual]
Returns id of an SCC that the given local state of the process belongs to.
Implements process_decomposition_t.
References dve_explicit_system_t::get_state_of_process().
int get_process_scc_type (state_t &) [virtual]
Returns type of an SCC that the given local state belongs to. Returned values: 0 means nonaccepting component, 1 means partially accepting component, and 2 means fully accepting component.
Implements process_decomposition_t.
References dve_explicit_system_t::get_state_of_process().
int get_scc_count () [virtual]
Returns the number of SCCs in the decomposition.
Implements process_decomposition_t.
int get_scc_type (int) [virtual]
Returns type of the given SCC, where 0 means nonaccepting component, 1 means partially accepting component, and 2 means fully accepting component.
Implements process_decomposition_t.
bool is_weak () [virtual]
Returns whether the process has a weak graph.
Implements process_decomposition_t.
void parse_process (std::size_t) [virtual]
Performs the decomposition of a process with a given (global) id.
Implements process_decomposition_t.
References dve_process_t::get_acceptance(), dve_process_t::get_initial_state(), dve_system_t::get_process(), dve_transition_t::get_state1_lid(), dve_transition_t::get_state2_lid(), dve_process_t::get_state_count(), dve_process_t::get_trans_count(), and dve_process_t::get_transition().
The documentation for this class was generated from the following files:
dve_process_decomposition.hh
dve_process_decomposition.cc
Reference Manual for Library, 2006 developed in ParaDiSe laboratory, Faculty of Informatics, Masaryk University